apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l407yhsoc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l407yhsoc-go 
  name: l407yhsoc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l407yhsoc-go 
